# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  crai-twiki-api:
    build:
      target: development
    image: crai-twiki-api-development
    container_name: crai-twiki-api-development
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./app:/home/node/app
      - ./test:/home/node/test
      - ./scripts:/home/node/scripts
      - ./package.json:/home/node/package.json
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST:-host.docker.internal}
      POSTGRES_DB: ${POSTGRES_DB:-crai-twiki-api}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ppp}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME:-postgres}
      

  crai-twiki-api-postgres:
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
